Repository netbox-community/netbox-topology-views, pull requests merged in 2022-12, with the labels that each got.

#193 Feature: Add customisable icons in topology
  README.md
  netbox_topology_views/__init__.py
  netbox_topology_views/api/__init__.py
  netbox_topology_views/api/serializers.py
  netbox_topology_views/api/urls.py
  netbox_topology_views/api/views.py
  netbox_topology_views/filters.py
  netbox_topology_views/forms.py
  netbox_topology_views/migrations/0001_initial.py
  netbox_topology_views/migrations/__init__.py
  netbox_topology_views/models.py
  netbox_topology_views/navigation.py
  netbox_topology_views/static/netbox_topology_views/css/app.css
  netbox_topology_views/static/netbox_topology_views/js/app.js
  netbox_topology_views/static/netbox_topology_views/js/images.js
  netbox_topology_views/static/netbox_topology_views/js/images.js.map
  netbox_topology_views/static_dev/bundle.js
  netbox_topology_views/static_dev/css/app.scss
  netbox_topology_views/static_dev/js/csrftoken.js
  netbox_topology_views/static_dev/js/home.js
  netbox_topology_views/static_dev/js/images.js
  netbox_topology_views/static_dev/js/toast.js
  netbox_topology_views/templates/netbox_topology_views/images.html
  netbox_topology_views/templates/netbox_topology_views/index.html
  netbox_topology_views/templates/netbox_topology_views/toasts.html
  netbox_topology_views/urls.py
  netbox_topology_views/utils.py
  netbox_topology_views/views.py
  requirements.txt
  setup.py
Labels: enhancement

#220 Topology button in Site View
  netbox_topology_views/static/netbox_topology_views/js/app.js
  netbox_topology_views/static_dev/js/home.js
  netbox_topology_views/template_content.py
  netbox_topology_views/templates/netbox_topology_views/htmx_topology.html
  netbox_topology_views/templates/netbox_topology_views/site_button.html
  netbox_topology_views/views.py
Labels: status: accepted

#213 initial update of docs
  dev_setup/README.md
Labels: status: accepted

#221 add check for python3.9
  netbox_topology_views/utils.py
Labels: status: accepted

#222 Release 3.1.1
  netbox_topology_views/__init__.py
  netbox_topology_views/static_dev/package-lock.json
  netbox_topology_views/static_dev/package.json
  setup.py
Labels: status: accepted

#229 Link to netbox-docker wiki for install in docker
  .github/workflows/docker-publish.yml
  Dockerfile
  README.md
  docker/plugin_requirements.txt
Labels: status: accepted, type: documentation

#227 Closes #160: feature save filters
  netbox_topology_views/forms.py
  netbox_topology_views/static/netbox_topology_views/css/app.css
  netbox_topology_views/static_dev/css/app.scss
  netbox_topology_views/templates/netbox_topology_views/index.html
  netbox_topology_views/views.py
Labels: type: feature, status: accepted
